# Standard Industrial Classification (SIC) codes used by SEC EDGAR
# Source: https://www.sec.gov/info/edgar/siccodes.htm

SIC_CODES = {
    # --- Agriculture, Forestry & Fishing ---
    "0100": "Crops",
    "0200": "Livestock",
    "0700": "Agricultural Services",
    "0800": "Forestry",
    "0900": "Fishing, Hunting & Trapping",

    # --- Mining ---
    "1000": "Metal Mining",
    "1040": "Gold & Silver Ores Mining",
    "1090": "Metal Mining Services",
    "1094": "Uranium-Radium-Vanadium Ores",
    "1221": "Bituminous Coal & Lignite Surface Mining",
    "1311": "Crude Petroleum & Natural Gas",
    "1381": "Drilling Oil & Gas Wells",
    "1382": "Oil & Gas Field Services",
    "1400": "Mining & Quarrying of Nonmetallic Minerals",

    # --- Construction ---
    "1500": "Building Construction",
    "1520": "General Building Contractors - Residential Buildings",
    "1531": "Operative Builders",
    "1600": "Heavy Construction (Except Building Construction)",
    "1700": "Special Trade Contractors",
    "1731": "Electrical Work",

    # --- Manufacturing ---
    "2000": "Food & Kindred Products",
    "2011": "Meat Packing Plants",
    "2090": "Food Preparations, NEC",
    "2100": "Tobacco Products",
    "2200": "Textile Mill Products",
    "2300": "Apparel & Other Finished Products",
    "2400": "Lumber & Wood Products",
    "2500": "Furniture & Fixtures",
    "2600": "Paper & Allied Products",
    "2700": "Printing, Publishing & Allied Industries",
    "2750": "Commercial Printing",
    "2800": "Chemicals & Allied Products",
    "2830": "Drugs",
    "2833": "Pharmaceutical Preparations",
    "2835": "In Vitro & In Vivo Diagnostic Substances",
    "2836": "Biological Products (No Diagnostic Substances)",
    "2860": "Industrial Chemicals & Synthetics",
    "2900": "Petroleum Refining & Related Industries",
    "2911": "Petroleum Refining",
    "3000": "Rubber & Miscellaneous Plastics Products",
    "3100": "Leather & Leather Products",
    "3200": "Stone, Clay, Glass & Concrete Products",
    "3300": "Primary Metal Industries",
    "3310": "Steel Works, Blast Furnaces",
    "3400": "Fabricated Metal Products",
    "3500": "Industrial & Commercial Machinery",
    "3559": "Special Industry Machinery, NEC",
    "3570": "Computer & Office Equipment",
    "3571": "Electronic Computers",
    "3572": "Computer Storage Devices",
    "3576": "Computer Communications Equipment",
    "3577": "Computer Peripheral Equipment, NEC",
    "3600": "Electronic & Other Electrical Equipment",
    "3621": "Motors & Generators",
    "3661": "Telephone & Telegraph Apparatus",
    "3669": "Communications Equipment, NEC",
    "3672": "Printed Circuit Boards",
    "3674": "Semiconductors & Related Devices",
    "3679": "Electronic Components, NEC",
    "3690": "Electronic & Other Electrical Equipment, NEC",
    "3700": "Transportation Equipment",
    "3711": "Motor Vehicles & Passenger Car Bodies",
    "3714": "Motor Vehicle Parts & Accessories",
    "3721": "Aircraft",
    "3760": "Guided Missiles & Space Vehicles",
    "3812": "Defense Electronics",
    "3821": "Laboratory Apparatus & Furniture",
    "3825": "Instruments for Measuring",
    "3841": "Surgical & Medical Instruments & Apparatus",
    "3842": "Orthopedic, Prosthetic & Surgical Appliances",
    "3845": "Electromedical Equipment",
    "3900": "Miscellaneous Manufacturing Industries",

    # --- Transportation & Public Utilities ---
    "4000": "Railroad Transportation",
    "4011": "Railroads, Line-Haul Operating",
    "4100": "Local & Suburban Transit",
    "4200": "Trucking & Warehousing",
    "4210": "Trucking & Courier Services (No Air)",
    "4400": "Water Transportation",
    "4500": "Transportation by Air",
    "4510": "Air Transportation, Scheduled",
    "4522": "Air Transportation, Nonscheduled",
    "4600": "Pipelines, Except Natural Gas",
    "4700": "Transportation Services",
    "4731": "Freight Transportation Arrangement",
    "4800": "Communications",
    "4810": "Telephone Communications",
    "4812": "Radiotelephone Communications",
    "4813": "Telephone Communications (No Radio Telephone)",
    "4820": "Telegraph & Other Message Communications",
    "4830": "Radio & Television Broadcasting",
    "4833": "Television Broadcasting Stations",
    "4841": "Cable & Other Pay Television Services",
    "4899": "Communications Services, NEC",
    "4900": "Electric, Gas & Sanitary Services",
    "4911": "Electric Services",
    "4924": "Natural Gas Distribution",
    "4941": "Water Supply",
    "4950": "Sanitary Services",
    "4991": "Cogeneration Services & Small Power Producers",

    # --- Wholesale Trade ---
    "5000": "Durable Goods",
    "5010": "Motor Vehicle & Motor Vehicle Parts & Supplies",
    "5040": "Professional & Commercial Equipment",
    "5045": "Computers & Computer Peripherals & Software",
    "5060": "Electrical Apparatus & Equipment",
    "5065": "Electronic Parts & Equipment",
    "5080": "Industrial & Commercial Machinery",
    "5094": "Jewelry, Watches, Precious Stones & Metals",
    "5100": "Non-Durable Goods",
    "5110": "Paper & Paper Products",
    "5122": "Drugs, Drug Proprietaries & Druggists' Sundries",
    "5140": "Groceries & Related Products",
    "5190": "Misc. Non-Durable Goods",

    # --- Retail Trade ---
    "5200": "Retail - Building Materials, Hardware, Garden Supply",
    "5211": "Retail - Lumber & Building Material Dealers",
    "5300": "Retail - General Merchandise Stores",
    "5311": "Retail - Department Stores",
    "5331": "Retail - Variety Stores",
    "5400": "Retail - Food Stores",
    "5411": "Retail - Grocery Stores",
    "5500": "Retail - Auto Dealers & Gas Stations",
    "5531": "Retail - Auto & Home Supply Stores",
    "5600": "Retail - Apparel & Accessory Stores",
    "5621": "Retail - Women's Clothing Stores",
    "5651": "Retail - Family Clothing Stores",
    "5700": "Retail - Furniture & Homefurnishings",
    "5712": "Retail - Furniture Stores",
    "5734": "Retail - Computer & Computer Software Stores",
    "5800": "Retail - Eating & Drinking Places",
    "5812": "Retail - Eating Places",
    "5900": "Retail - Misc. Retail",
    "5912": "Retail - Drug Stores & Proprietary Stores",
    "5940": "Retail - Sporting Goods & Hobby",
    "5945": "Retail - Hobby, Toy & Game Shops",
    "5961": "Retail - Catalog & Mail-Order Houses",

    # --- Finance, Insurance & Real Estate ---
    "6020": "Mutual Savings Banks, NEC",
    "6021": "National Commercial Banks",
    "6022": "State Commercial Banks",
    "6025": "Savings Institution, Federally Chartered",
    "6026": "Savings Institutions, Not Federally-Chartered",
    "6029": "State Commercial Banks, NEC",
    "6035": "Savings Institution, Federally Chartered",
    "6036": "Savings Institutions, Not Federally-Chartered",
    "6099": "Functions Related to Depository Banking, NEC",
    "6110": "Federal & Federally-Sponsored Credit Agencies",
    "6111": "Federal & Federally-Sponsored Credit Agencies NEC",
    "6120": "Savings Institutions, Federally Chartered",
    "6141": "Personal Credit Institutions",
    "6153": "Short-Term Business Credit Institutions",
    "6159": "Federal-Sponsored Credit Agencies NEC",
    "6162": "Mortgage Bankers, Loan Correspondents",
    "6163": "Loan Brokers",
    "6172": "Finance Services",
    "6199": "Finance Services, NEC",
    "6200": "Security & Commodity Brokers, Dealers, Exchanges & Services",
    "6211": "Security Brokers, Dealers & Flotation Companies",
    "6221": "Commodity Contracts Dealers, Brokers",
    "6231": "Security & Commodity Exchanges",
    "6282": "Investment Advice",
    "6311": "Life Insurance",
    "6321": "Accident & Health Insurance",
    "6324": "Hospital & Medical Service Plans",
    "6331": "Fire, Marine & Casualty Insurance",
    "6351": "Surety Insurance",
    "6361": "Title Insurance",
    "6371": "Pension, Health & Welfare Funds",
    "6399": "Insurance Carriers, NEC",
    "6411": "Insurance Agents, Brokers & Service",
    "6500": "Real Estate",
    "6510": "Real Estate Dealers (For Their Own Account)",
    "6512": "Operators of Apartment Buildings",
    "6513": "Operators of Dwelling Buildings, NEC",
    "6514": "Operators of Dwellings Buildings, NEC",
    "6515": "Mobile Home Site Operators & Mobile Home Dealers",
    "6531": "Real Estate Dealers (For Their Own Account) NEC",
    "6552": "Land Subdividers & Developers (No Cemeteries)",
    "6553": "Cemetery Subdividers & Developers",
    "6710": "Holding Offices",
    "6712": "State Chartered Banks, Federal Reserve Members",
    "6719": "Offices of Holding Companies, NEC",
    "6720": "Investment Offices",
    "6726": "Investment Offices, NEC",
    "6770": "Blank Checks",
    "6792": "Investment Trusts, NEC",
    "6794": "Patent Owners & Lessors",
    "6798": "Real Estate Investment Trusts",
    "6799": "Investors, NEC",

    # --- Services ---
    "7000": "Hotels & Other Lodging Places",
    "7011": "Hotels & Motels",
    "7200": "Personal Services",
    "7372": "Prepackaged Software",
    "7371": "Computer Programming, Data Processing",
    "7373": "Computer Integrated Systems Design",
    "7374": "Computer Processing & Data Preparation",
    "7375": "Computer Rental & Leasing",
    "7379": "Services-Computer Related Services, NEC",
    "7380": "Security & Commodity Services",
    "7389": "Services-Misc Business Services",
    "7500": "Auto Repair, Services & Parking",
    "7600": "Miscellaneous Repair Services",
    "7812": "Services-Motion Picture, Videotape Production",
    "7900": "Amusement & Recreation Services",
    "7948": "Racing, Including Track Operations",
    "8000": "Health Services",
    "8011": "Offices & Clinics Of Doctors Of Medicine",
    "8049": "Offices & Clinics Of Other Health Practitioners",
    "8051": "Skilled Nursing Care Facilities",
    "8060": "Hospitals",
    "8062": "General Medical & Surgical Hospitals",
    "8071": "Medical Laboratories",
    "8082": "Home Health Care Services",
    "8090": "Health Services, NEC",
    "8099": "Health Services, NEC",
    "8100": "Legal Services",
    "8200": "Educational Services",
    "8300": "Social Services",
    "8400": "Museums, Art Galleries, Botanical & Zoological Gardens",
    "8600": "Membership Organizations",
    "8711": "Engineering Services",
    "8731": "Commercial Physical & Biological Research",
    "8742": "Management Consulting Services",
    "8900": "Services, NEC",

    # --- Public Administration ---
    "9100": "Executive, Legislative & General Government",
    "9200": "Justice, Public Order & Safety",
    "9300": "Finance, Taxation & Monetary Policy",
    "9400": "Administration of Human Resource Programs",
    "9500": "Environmental Quality & Housing Programs",
    "9600": "Administration of Economic Programs",
    "9700": "National Security & International Affairs",
    "9900": "Nonclassifiable Establishments",
}

# Group codes by sector for UI display
SIC_SECTORS = {
    "Agriculture, Forestry & Fishing": [k for k in SIC_CODES if "01" <= k[:2] <= "09"],
    "Mining": [k for k in SIC_CODES if "10" <= k[:2] <= "14"],
    "Construction": [k for k in SIC_CODES if "15" <= k[:2] <= "17"],
    "Manufacturing": [k for k in SIC_CODES if "20" <= k[:2] <= "39"],
    "Transportation & Utilities": [k for k in SIC_CODES if "40" <= k[:2] <= "49"],
    "Wholesale Trade": [k for k in SIC_CODES if "50" <= k[:2] <= "51"],
    "Retail Trade": [k for k in SIC_CODES if "52" <= k[:2] <= "59"],
    "Finance, Insurance & Real Estate": [k for k in SIC_CODES if "60" <= k[:2] <= "67"],
    "Services": [k for k in SIC_CODES if "70" <= k[:2] <= "89"],
    "Public Administration": [k for k in SIC_CODES if "91" <= k[:2] <= "99"],
}
